micronaut:
  application:
    name: quotation-service
  config-client:
    enabled: true
  server:
    port: 8080
    cors:
      enabled: true

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"


#tracing:
#  zipkin:
#    http:
#      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
#    enabled: true
#    sampler:
#      probability: 1
#

