micronaut:
  application:
    name: fipe-service
  config-client:
    enabled: true
  server:
    port: 8080
    cors:
      enabled: true

gateways:
  fipe:
    endpoint: http://fipeapi.appspot.com/api/1

#consul:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

# datasources:
#   default:
#     dbCreate: create-drop
#     url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#     username: ${JDBC_USER:sa}
#     password: ${JDBC_PASSWORD:""}
#     driverClassName: ${JDBC_DRIVER:org.h2.Driver}
